'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  direction: Direction;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    // Header
    'header.location': 'الرياض، المملكة العربية السعودية',
    'header.about': 'من نحن',
    'header.contact': 'تواصل معنا',
    'header.help': 'المساعدة',
    'header.home': 'الرئيسية',
    'header.services': 'الخدمات',
    'header.providers': 'مقدمو الخدمات',
    'header.howItWorks': 'كيف تعمل',
    'header.becomeProvider': 'انضم كمزود خدمة',
    'header.notifications': 'الإشعارات',
    'header.markAllRead': 'تعليم الكل كمقروء',
    'header.viewAll': 'عرض جميع الإشعارات',
    'header.profile': 'الملف الشخصي',
    'header.myBookings': 'حجوزاتي',
    'header.favorites': 'المفضلة',
    'header.settings': 'الإعدادات',
    'header.logout': 'تسجيل الخروج',
    'header.language': 'اللغة',
    'header.theme': 'المظهر',
    'header.lightMode': 'الوضع الفاتح',
    'header.darkMode': 'الوضع الداكن',
    'header.systemMode': 'حسب النظام',

    // Homepage
    'home.hero.badge': 'منصة موثوقة لأكثر من 50,000 عميل',
    'home.hero.title': 'احصل على خدمات موثوقة بلمسة واحدة',
    'home.hero.subtitle': 'نربطك بأفضل مقدمي الخدمات المعتمدين في منطقتك. جودة مضمونة ووقت محدد.',
    'home.hero.searchPlaceholder': 'ما الخدمة التي تحتاجها؟',
    'home.hero.searchButton': 'ابحث الآن',
    'home.hero.guarantee': 'خدمات مضمونة 100%',
    'home.hero.fastDelivery': 'توصيل سريع',
    'home.hero.certified': 'مقدمو خدمات معتمدون',
    'home.categories.title': 'تصفح حسب الفئة',
    'home.categories.subtitle': 'اختر الفئة المناسبة لاحتياجاتك',
    'home.featured.title': 'الخدمات المميزة',
    'home.featured.subtitle': 'أكثر الخدمات طلباً هذا الأسبوع',
    'home.providers.title': 'مقدمو خدمات مميزون',
    'home.providers.subtitle': 'أفضل مقدمي الخدمات المعتمدين',
    'home.cta.title': 'هل أنت مقدم خدمة؟',
    'home.cta.subtitle': 'انضم إلى منصتنا وابدأ في تقديم خدماتك لآلاف العملاء',
    'home.cta.register': 'سجل كمقدم خدمة',
    'home.cta.learnMore': 'اعرف المزيد',
    'home.why.title': 'لماذا تختار منصتنا؟',
    'home.why.subtitle': 'نوفر لك تجربة فريدة ومضمونة',
    'home.why.certified': 'مقدمو خدمات معتمدون',
    'home.why.certifiedDesc': 'جميع مقدمي الخدمات معتمدون ومؤهلون بالكامل',
    'home.why.fast': 'خدمة سريعة',
    'home.why.fastDesc': 'احجز واحصل على الخدمة في نفس اليوم',
    'home.why.quality': 'جودة مضمونة',
    'home.why.qualityDesc': 'ضمان الجودة أو استرجاع المبلغ بالكامل',
    'home.why.coverage': 'تغطية واسعة',
    'home.why.coverageDesc': 'نغطي جميع مناطق المملكة',

    // Common
    'common.viewAll': 'عرض الكل',
    'common.bookNow': 'احجز الآن',
    'common.sar': 'ر.س',
    'common.minutes': 'دقيقة',
    'common.rating': 'تقييم',
    'common.reviews': 'تقييمات',
    'common.services': 'خدمات',
    'common.verified': 'معتمد',
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.confirm': 'تأكيد',

    // Auth
    'auth.login.title': 'مرحباً بعودتك',
    'auth.login.subtitle': 'سجل الدخول للوصول إلى حسابك',
    'auth.login.email': 'البريد الإلكتروني',
    'auth.login.password': 'كلمة المرور',
    'auth.login.rememberMe': 'تذكرني',
    'auth.login.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.login.button': 'تسجيل الدخول',
    'auth.login.noAccount': 'ليس لديك حساب؟',
    'auth.login.signUp': 'سجل الآن',
    'auth.signup.title': 'إنشاء حساب جديد',
    'auth.signup.subtitle': 'انضم إلينا واحصل على أفضل الخدمات',
    'auth.signup.fullName': 'الاسم الكامل',
    'auth.signup.phone': 'رقم الجوال',
    'auth.signup.confirmPassword': 'تأكيد كلمة المرور',
    'auth.signup.agree': 'أوافق على',
    'auth.signup.terms': 'الشروط والأحكام',
    'auth.signup.privacy': 'سياسة الخصوصية',
    'auth.signup.button': 'إنشاء حساب',
    'auth.signup.haveAccount': 'لديك حساب بالفعل؟',
    'auth.signup.login': 'سجل الدخول',
    'auth.backToHome': 'العودة للرئيسية',

    // Footer
    'footer.description': 'منصة رائدة لربط العملاء بمقدمي الخدمات المعتمدين. نوفر لك خدمات موثوقة وعالية الجودة في جميع المجالات.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.support': 'الدعم والمساعدة',
    'footer.helpCenter': 'مركز المساعدة',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.terms': 'الشروط والأحكام',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.refund': 'سياسة الاسترجاع',
    'footer.contactUs': 'تواصل معنا',
    'footer.newsletter': 'اشترك في النشرة البريدية',
    'footer.emailPlaceholder': 'بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.cookies': 'سياسة الكوكيز',

    // Providers Page
    'providers.hero.title': 'تصفح أفضل مقدمي الخدمات',
    'providers.hero.subtitle': 'مقدمو خدمات معتمدون وموثوقون في جميع التخصصات',
    'providers.filter.all': 'الكل',
    'providers.filter.topRated': 'الأعلى تقييماً',
    'providers.filter.mostBooked': 'الأكثر حجزاً',
    'providers.filter.verified': 'معتمد فقط',
    'providers.stats.providers': 'مقدم خدمة',
    'providers.stats.services': 'خدمة مكتملة',
    'providers.stats.rating': 'متوسط التقييم',
    'providers.viewProfile': 'عرض الملف الشخصي',
    'providers.completedJobs': 'خدمة مكتملة',
    'providers.memberSince': 'عضو منذ',

    // How It Works Page
    'howItWorks.hero.title': 'كيف تعمل المنصة؟',
    'howItWorks.hero.subtitle': 'خطوات بسيطة للحصول على الخدمة التي تحتاجها',
    'howItWorks.customer.title': 'للعملاء',
    'howItWorks.customer.subtitle': 'احصل على الخدمة في 4 خطوات سهلة',
    'howItWorks.customer.step1.title': 'ابحث عن الخدمة',
    'howItWorks.customer.step1.desc': 'تصفح مئات الخدمات أو استخدم البحث الذكي للعثور على ما تحتاج',
    'howItWorks.customer.step2.title': 'اختر مقدم الخدمة',
    'howItWorks.customer.step2.desc': 'قارن بين مقدمي الخدمات واختر الأفضل بناءً على التقييمات والأسعار',
    'howItWorks.customer.step3.title': 'احجز موعدك',
    'howItWorks.customer.step3.desc': 'حدد الوقت والمكان المناسب واختر طريقة الدفع',
    'howItWorks.customer.step4.title': 'احصل على الخدمة',
    'howItWorks.customer.step4.desc': 'مقدم الخدمة سيصل في الموعد المحدد وينفذ الخدمة بجودة عالية',
    'howItWorks.provider.title': 'لمقدمي الخدمات',
    'howItWorks.provider.subtitle': 'انضم واربح المال من خلال تقديم خدماتك',
    'howItWorks.provider.step1.title': 'سجل حسابك',
    'howItWorks.provider.step1.desc': 'أنشئ حساب مزود خدمة وأكمل معلومات ملفك الشخصي',
    'howItWorks.provider.step2.title': 'أضف خدماتك',
    'howItWorks.provider.step2.desc': 'حدد الخدمات التي تقدمها مع الأسعار والمواعيد المتاحة',
    'howItWorks.provider.step3.title': 'اقبل الحجوزات',
    'howItWorks.provider.step3.desc': 'ستصلك طلبات الحجز، راجعها واقبل ما يناسبك',
    'howItWorks.provider.step4.title': 'نفذ واربح',
    'howItWorks.provider.step4.desc': 'نفذ الخدمة واحصل على أموالك بسهولة وأمان',
    'howItWorks.features.title': 'لماذا نحن الأفضل؟',
    'howItWorks.features.secure.title': 'دفع آمن',
    'howItWorks.features.secure.desc': 'نظام دفع محمي بالكامل وضمان استرجاع الأموال',
    'howItWorks.features.support.title': 'دعم على مدار الساعة',
    'howItWorks.features.support.desc': 'فريق الدعم جاهز لمساعدتك في أي وقت',
    'howItWorks.features.quality.title': 'ضمان الجودة',
    'howItWorks.features.quality.desc': 'جميع مقدمي الخدمات معتمدون ومؤهلون',
    'howItWorks.features.fast.title': 'سريع وسهل',
    'howItWorks.features.fast.desc': 'احجز واحصل على الخدمة في نفس اليوم',
    'howItWorks.cta.customer': 'ابدأ الحجز الآن',
    'howItWorks.cta.provider': 'انضم كمقدم خدمة',

    // Become Provider Page
    'becomeProvider.hero.title': 'انضم كمقدم خدمة',
    'becomeProvider.hero.subtitle': 'ابدأ في كسب المال من خلال تقديم خدماتك لآلاف العملاء',
    'becomeProvider.hero.button': 'سجل الآن مجاناً',
    'becomeProvider.benefits.title': 'لماذا تنضم إلى منصتنا؟',
    'becomeProvider.benefits.customers.title': 'آلاف العملاء',
    'becomeProvider.benefits.customers.desc': 'وصول فوري لآلاف العملاء الذين يبحثون عن خدماتك',
    'becomeProvider.benefits.flexible.title': 'مرونة كاملة',
    'becomeProvider.benefits.flexible.desc': 'اختر أوقات عملك وحدد أسعارك بنفسك',
    'becomeProvider.benefits.payments.title': 'دفعات سريعة',
    'becomeProvider.benefits.payments.desc': 'احصل على أموالك بسرعة وأمان بعد كل خدمة',
    'becomeProvider.benefits.support.title': 'دعم مستمر',
    'becomeProvider.benefits.support.desc': 'فريق دعم متاح لمساعدتك في أي وقت',
    'becomeProvider.benefits.marketing.title': 'تسويق مجاني',
    'becomeProvider.benefits.marketing.desc': 'نسوق لخدماتك ونجلب لك العملاء',
    'becomeProvider.benefits.tools.title': 'أدوات احترافية',
    'becomeProvider.benefits.tools.desc': 'لوحة تحكم متقدمة لإدارة حجوزاتك وأرباحك',
    'becomeProvider.requirements.title': 'متطلبات الانضمام',
    'becomeProvider.requirements.subtitle': 'بسيطة وسهلة',
    'becomeProvider.requirements.docs.title': 'الوثائق المطلوبة',
    'becomeProvider.requirements.docs.item1': 'بطاقة هوية سارية المفعول',
    'becomeProvider.requirements.docs.item2': 'شهادة / رخصة مزاولة المهنة (إن وجدت)',
    'becomeProvider.requirements.docs.item3': 'صورة شخصية واضحة',
    'becomeProvider.requirements.docs.item4': 'معلومات الحساب البنكي',
    'becomeProvider.requirements.skills.title': 'المهارات والخبرة',
    'becomeProvider.requirements.skills.item1': 'خبرة في المجال المطلوب',
    'becomeProvider.requirements.skills.item2': 'التزام بالمواعيد',
    'becomeProvider.requirements.skills.item3': 'مهارات تواصل جيدة',
    'becomeProvider.requirements.skills.item4': 'جودة عالية في العمل',
    'becomeProvider.steps.title': 'خطوات التسجيل',
    'becomeProvider.steps.step1': 'املأ نموذج التسجيل',
    'becomeProvider.steps.step2': 'ارفع الوثائق المطلوبة',
    'becomeProvider.steps.step3': 'انتظر الموافقة (24-48 ساعة)',
    'becomeProvider.steps.step4': 'ابدأ في تلقي الحجوزات',
    'becomeProvider.stats.providers': 'مقدم خدمة نشط',
    'becomeProvider.stats.earnings': 'متوسط الأرباح الشهرية',
    'becomeProvider.stats.bookings': 'حجز شهرياً',
    'becomeProvider.cta.title': 'جاهز للبدء؟',
    'becomeProvider.cta.subtitle': 'انضم لآلاف مقدمي الخدمات الناجحين',
    'becomeProvider.cta.button': 'سجل الآن',

    // Services Page
    'services.title': 'تصفح الخدمات',
    'services.subtitle': 'اكتشف أفضل الخدمات المتاحة في منطقتك',
    'services.found': 'تم العثور على',
    'services.servicesText': 'خدمة',
    'services.filters': 'الفلاتر',
    'services.sort': 'الترتيب',
    'services.sort.popular': 'الأكثر طلباً',
    'services.sort.rating': 'الأعلى تقييماً',
    'services.sort.priceLow': 'السعر: من الأقل للأعلى',
    'services.sort.priceHigh': 'السعر: من الأعلى للأقل',
    'services.sort.newest': 'الأحدث',
    'services.filterResults': 'تصفية النتائج',
    'services.reset': 'إعادة تعيين',
    'services.priceRange': 'نطاق السعر',
    'services.ratingFilter': 'التقييم',
    'services.andUp': 'فأكثر',
    'services.city': 'المدينة',
    'services.availability': 'التوفر',
    'services.availableNow': 'متاح الآن',
    'services.verifiedOnly': 'مقدمو خدمات معتمدون',
    'services.notAvailable': 'غير متاح حالياً',
    'services.book': 'احجز',

    // Service Details Page
    'serviceDetails.verifiedProvider': 'مقدم خدمة معتمد',
    'serviceDetails.rating': 'تقييم',
    'serviceDetails.description': 'وصف الخدمة',
    'serviceDetails.includes': 'ما تشمله الخدمة',
    'serviceDetails.addons': 'إضافات اختيارية',
    'serviceDetails.provider': 'مقدم الخدمة',
    'serviceDetails.viewProfile': 'عرض الملف الشخصي',
    'serviceDetails.contactUs': 'تواصل معنا',
    'serviceDetails.reviews': 'التقييمات',
    'serviceDetails.reviewsCount': 'تقييم',
    'serviceDetails.ratingStats': 'إحصائيات التقييم',
    'serviceDetails.loadMore': 'عرض المزيد من التقييمات',
    'serviceDetails.memberSince': 'عضو منذ',
    'serviceDetails.completedJobs': 'خدمة مكتملة',
    'serviceDetails.save': 'وفر',
    'serviceDetails.bookNow': 'احجز الآن',
    'serviceDetails.bookLater': 'احجز لاحقاً',
    'serviceDetails.moneyBack': 'ضمان استرجاع المبلغ',
    'serviceDetails.certified': 'مقدم خدمة معتمد',
    'serviceDetails.sameDay': 'خدمة في نفس اليوم',

    // Booking Page
    'booking.title': 'إتمام الحجز',
    'booking.subtitle': 'اكمل البيانات لتأكيد حجزك',
    'booking.step.address': 'العنوان',
    'booking.step.datetime': 'التاريخ والوقت',
    'booking.step.review': 'مراجعة الطلب',
    'booking.step.payment': 'الدفع',
    'booking.selectAddress': 'اختر العنوان',
    'booking.selectAddressDesc': 'حدد عنوان تنفيذ الخدمة',
    'booking.addNewAddress': 'إضافة عنوان جديد',
    'booking.addressLabel': 'اسم العنوان',
    'booking.addressLabelPlaceholder': 'مثال: المنزل، العمل',
    'booking.address': 'العنوان',
    'booking.addressPlaceholder': 'الشارع والحي',
    'booking.cityLabel': 'المدينة',
    'booking.cityPlaceholder': 'الرياض',
    'booking.phone': 'رقم الهاتف',
    'booking.phonePlaceholder': '+966 5X XXX XXXX',
    'booking.additionalDetails': 'تفاصيل إضافية',
    'booking.additionalDetailsPlaceholder': 'رقم الفيلا، الدور، وصف المكان...',
    'booking.selectDateTime': 'اختر التاريخ والوقت',
    'booking.selectDateTimeDesc': 'حدد الموعد المناسب لك',
    'booking.date': 'التاريخ',
    'booking.availableTimes': 'الوقت المتاح',
    'booking.selectDateFirst': 'اختر التاريخ أولاً',
    'booking.optionalAddons': 'إضافات اختيارية',
    'booking.notes': 'ملاحظات إضافية (اختياري)',
    'booking.notesPlaceholder': 'أي تفاصيل إضافية تود إخبارنا بها...',
    'booking.reviewOrder': 'مراجعة الطلب',
    'booking.reviewOrderDesc': 'تأكد من صحة البيانات قبل المتابعة',
    'booking.serviceAddress': 'عنوان الخدمة',
    'booking.appointment': 'الموعد',
    'booking.at': 'في تمام الساعة',
    'booking.expectedDuration': 'المدة المتوقعة',
    'booking.addonsSelected': 'الإضافات',
    'booking.yourNotes': 'ملاحظاتك',
    'booking.paymentTitle': 'الدفع',
    'booking.paymentDesc': 'اختر طريقة الدفع المناسبة',
    'booking.discountCode': 'رمز الخصم',
    'booking.discountCodePlaceholder': 'أدخل رمز الخصم',
    'booking.apply': 'تطبيق',
    'booking.discountApplied': 'تم تطبيق خصم',
    'booking.creditCard': 'بطاقة ائتمانية',
    'booking.cardDescription': 'Visa, Mastercard, Mada',
    'booking.recommended': 'موصى به',
    'booking.wallet': 'المحفظة الإلكترونية',
    'booking.walletBalance': 'الرصيد',
    'booking.insufficientBalance': 'رصيد غير كافٍ',
    'booking.cashOnDelivery': 'الدفع عند الاستلام',
    'booking.cashDescription': 'ادفع نقداً عند تنفيذ الخدمة',
    'booking.cardNumber': 'رقم البطاقة',
    'booking.expiryDate': 'تاريخ الانتهاء',
    'booking.cardHolder': 'اسم حامل البطاقة',
    'booking.cardHolderPlaceholder': 'الاسم كما هو مكتوب على البطاقة',
    'booking.securePayment': 'جميع المعاملات مشفرة ومؤمنة بالكامل',
    'booking.previous': 'السابق',
    'booking.confirmBooking': 'تأكيد الحجز ودفع',
    'booking.orderSummary': 'ملخص الطلب',
    'booking.servicePrice': 'سعر الخدمة',
    'booking.discount': 'الخصم',
    'booking.total': 'الإجمالي',
    'booking.freeCancellation': 'إلغاء مجاني قبل 24 ساعة',

    // Categories
    'category.homeCleaning': 'تنظيف المنازل',
    'category.carMaintenance': 'صيانة السيارات',
    'category.techServices': 'خدمات تقنية',
    'category.generalMaintenance': 'صيانة عامة',
    'category.paintDecor': 'دهان وديكور',
    'category.electrical': 'كهرباء',

    // Cities
    'city.riyadh': 'الرياض',
    'city.jeddah': 'جدة',
    'city.dammam': 'الدمام',
    'city.makkah': 'مكة',
    'city.madinah': 'المدينة',
  },
  en: {
    // Header
    'header.location': 'Riyadh, Saudi Arabia',
    'header.about': 'About Us',
    'header.contact': 'Contact Us',
    'header.help': 'Help',
    'header.home': 'Home',
    'header.services': 'Services',
    'header.providers': 'Service Providers',
    'header.howItWorks': 'How It Works',
    'header.becomeProvider': 'Become a Provider',
    'header.notifications': 'Notifications',
    'header.markAllRead': 'Mark All as Read',
    'header.viewAll': 'View All Notifications',
    'header.profile': 'Profile',
    'header.myBookings': 'My Bookings',
    'header.favorites': 'Favorites',
    'header.settings': 'Settings',
    'header.logout': 'Logout',
    'header.language': 'Language',
    'header.theme': 'Theme',
    'header.lightMode': 'Light Mode',
    'header.darkMode': 'Dark Mode',
    'header.systemMode': 'System Default',

    // Homepage
    'home.hero.badge': 'Trusted platform by 50,000+ customers',
    'home.hero.title': 'Get Reliable Services with One Touch',
    'home.hero.subtitle': 'We connect you with the best certified service providers in your area. Guaranteed quality and timely delivery.',
    'home.hero.searchPlaceholder': 'What service do you need?',
    'home.hero.searchButton': 'Search Now',
    'home.hero.guarantee': '100% Service Guarantee',
    'home.hero.fastDelivery': 'Fast Delivery',
    'home.hero.certified': 'Certified Providers',
    'home.categories.title': 'Browse by Category',
    'home.categories.subtitle': 'Choose the category that suits your needs',
    'home.featured.title': 'Featured Services',
    'home.featured.subtitle': 'Most requested services this week',
    'home.providers.title': 'Featured Providers',
    'home.providers.subtitle': 'Best certified service providers',
    'home.cta.title': 'Are You a Service Provider?',
    'home.cta.subtitle': 'Join our platform and start providing services to thousands of customers',
    'home.cta.register': 'Register as Provider',
    'home.cta.learnMore': 'Learn More',
    'home.why.title': 'Why Choose Our Platform?',
    'home.why.subtitle': 'We provide you with a unique and guaranteed experience',
    'home.why.certified': 'Certified Providers',
    'home.why.certifiedDesc': 'All service providers are fully certified and qualified',
    'home.why.fast': 'Fast Service',
    'home.why.fastDesc': 'Book and get service on the same day',
    'home.why.quality': 'Quality Guarantee',
    'home.why.qualityDesc': 'Quality guarantee or full refund',
    'home.why.coverage': 'Wide Coverage',
    'home.why.coverageDesc': 'We cover all regions of the Kingdom',

    // Common
    'common.viewAll': 'View All',
    'common.bookNow': 'Book Now',
    'common.sar': 'SAR',
    'common.minutes': 'minutes',
    'common.rating': 'rating',
    'common.reviews': 'reviews',
    'common.services': 'services',
    'common.verified': 'Verified',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.confirm': 'Confirm',

    // Auth
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to access your account',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.rememberMe': 'Remember me',
    'auth.login.forgotPassword': 'Forgot password?',
    'auth.login.button': 'Sign In',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.signUp': 'Sign Up',
    'auth.signup.title': 'Create New Account',
    'auth.signup.subtitle': 'Join us and get the best services',
    'auth.signup.fullName': 'Full Name',
    'auth.signup.phone': 'Phone Number',
    'auth.signup.confirmPassword': 'Confirm Password',
    'auth.signup.agree': 'I agree to',
    'auth.signup.terms': 'Terms and Conditions',
    'auth.signup.privacy': 'Privacy Policy',
    'auth.signup.button': 'Create Account',
    'auth.signup.haveAccount': 'Already have an account?',
    'auth.signup.login': 'Sign In',
    'auth.backToHome': 'Back to Home',

    // Footer
    'footer.description': 'A leading platform connecting customers with certified service providers. We provide you with reliable and high-quality services in all areas.',
    'footer.quickLinks': 'Quick Links',
    'footer.support': 'Support & Help',
    'footer.helpCenter': 'Help Center',
    'footer.faq': 'FAQ',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.refund': 'Refund Policy',
    'footer.contactUs': 'Contact Us',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.emailPlaceholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved',
    'footer.cookies': 'Cookie Policy',

    // Providers Page
    'providers.hero.title': 'Browse Top Service Providers',
    'providers.hero.subtitle': 'Certified and trusted service providers in all specialties',
    'providers.filter.all': 'All',
    'providers.filter.topRated': 'Top Rated',
    'providers.filter.mostBooked': 'Most Booked',
    'providers.filter.verified': 'Verified Only',
    'providers.stats.providers': 'Service Providers',
    'providers.stats.services': 'Completed Services',
    'providers.stats.rating': 'Average Rating',
    'providers.viewProfile': 'View Profile',
    'providers.completedJobs': 'Completed Jobs',
    'providers.memberSince': 'Member Since',

    // How It Works Page
    'howItWorks.hero.title': 'How Does It Work?',
    'howItWorks.hero.subtitle': 'Simple steps to get the service you need',
    'howItWorks.customer.title': 'For Customers',
    'howItWorks.customer.subtitle': 'Get service in 4 easy steps',
    'howItWorks.customer.step1.title': 'Search for Service',
    'howItWorks.customer.step1.desc': 'Browse hundreds of services or use smart search to find what you need',
    'howItWorks.customer.step2.title': 'Choose Provider',
    'howItWorks.customer.step2.desc': 'Compare providers and choose the best based on ratings and prices',
    'howItWorks.customer.step3.title': 'Book Your Appointment',
    'howItWorks.customer.step3.desc': 'Set the time and place that suits you and choose payment method',
    'howItWorks.customer.step4.title': 'Get the Service',
    'howItWorks.customer.step4.desc': 'Provider will arrive on time and deliver high-quality service',
    'howItWorks.provider.title': 'For Service Providers',
    'howItWorks.provider.subtitle': 'Join and earn money by providing your services',
    'howItWorks.provider.step1.title': 'Register Your Account',
    'howItWorks.provider.step1.desc': 'Create a provider account and complete your profile information',
    'howItWorks.provider.step2.title': 'Add Your Services',
    'howItWorks.provider.step2.desc': 'Specify the services you offer with prices and available times',
    'howItWorks.provider.step3.title': 'Accept Bookings',
    'howItWorks.provider.step3.desc': 'You will receive booking requests, review and accept what suits you',
    'howItWorks.provider.step4.title': 'Deliver & Earn',
    'howItWorks.provider.step4.desc': 'Deliver the service and get your money easily and securely',
    'howItWorks.features.title': 'Why We Are The Best?',
    'howItWorks.features.secure.title': 'Secure Payment',
    'howItWorks.features.secure.desc': 'Fully protected payment system with money-back guarantee',
    'howItWorks.features.support.title': '24/7 Support',
    'howItWorks.features.support.desc': 'Support team ready to help you anytime',
    'howItWorks.features.quality.title': 'Quality Guarantee',
    'howItWorks.features.quality.desc': 'All service providers are certified and qualified',
    'howItWorks.features.fast.title': 'Fast & Easy',
    'howItWorks.features.fast.desc': 'Book and get service on the same day',
    'howItWorks.cta.customer': 'Start Booking Now',
    'howItWorks.cta.provider': 'Become a Provider',

    // Become Provider Page
    'becomeProvider.hero.title': 'Become a Service Provider',
    'becomeProvider.hero.subtitle': 'Start earning money by providing your services to thousands of customers',
    'becomeProvider.hero.button': 'Register Now for Free',
    'becomeProvider.benefits.title': 'Why Join Our Platform?',
    'becomeProvider.benefits.customers.title': 'Thousands of Customers',
    'becomeProvider.benefits.customers.desc': 'Instant access to thousands of customers looking for your services',
    'becomeProvider.benefits.flexible.title': 'Full Flexibility',
    'becomeProvider.benefits.flexible.desc': 'Choose your working hours and set your own prices',
    'becomeProvider.benefits.payments.title': 'Fast Payments',
    'becomeProvider.benefits.payments.desc': 'Get your money quickly and securely after each service',
    'becomeProvider.benefits.support.title': 'Continuous Support',
    'becomeProvider.benefits.support.desc': 'Support team available to help you anytime',
    'becomeProvider.benefits.marketing.title': 'Free Marketing',
    'becomeProvider.benefits.marketing.desc': 'We market your services and bring you customers',
    'becomeProvider.benefits.tools.title': 'Professional Tools',
    'becomeProvider.benefits.tools.desc': 'Advanced dashboard to manage your bookings and earnings',
    'becomeProvider.requirements.title': 'Joining Requirements',
    'becomeProvider.requirements.subtitle': 'Simple and Easy',
    'becomeProvider.requirements.docs.title': 'Required Documents',
    'becomeProvider.requirements.docs.item1': 'Valid ID card',
    'becomeProvider.requirements.docs.item2': 'Certificate / Professional license (if any)',
    'becomeProvider.requirements.docs.item3': 'Clear personal photo',
    'becomeProvider.requirements.docs.item4': 'Bank account information',
    'becomeProvider.requirements.skills.title': 'Skills & Experience',
    'becomeProvider.requirements.skills.item1': 'Experience in the required field',
    'becomeProvider.requirements.skills.item2': 'Commitment to deadlines',
    'becomeProvider.requirements.skills.item3': 'Good communication skills',
    'becomeProvider.requirements.skills.item4': 'High quality work',
    'becomeProvider.steps.title': 'Registration Steps',
    'becomeProvider.steps.step1': 'Fill out registration form',
    'becomeProvider.steps.step2': 'Upload required documents',
    'becomeProvider.steps.step3': 'Wait for approval (24-48 hours)',
    'becomeProvider.steps.step4': 'Start receiving bookings',
    'becomeProvider.stats.providers': 'Active Providers',
    'becomeProvider.stats.earnings': 'Average Monthly Earnings',
    'becomeProvider.stats.bookings': 'Monthly Bookings',
    'becomeProvider.cta.title': 'Ready to Start?',
    'becomeProvider.cta.subtitle': 'Join thousands of successful service providers',
    'becomeProvider.cta.button': 'Register Now',

    // Services Page
    'services.title': 'Browse Services',
    'services.subtitle': 'Discover the best services available in your area',
    'services.found': 'Found',
    'services.servicesText': 'services',
    'services.filters': 'Filters',
    'services.sort': 'Sort by',
    'services.sort.popular': 'Most Popular',
    'services.sort.rating': 'Highest Rated',
    'services.sort.priceLow': 'Price: Low to High',
    'services.sort.priceHigh': 'Price: High to Low',
    'services.sort.newest': 'Newest',
    'services.filterResults': 'Filter Results',
    'services.reset': 'Reset',
    'services.priceRange': 'Price Range',
    'services.ratingFilter': 'Rating',
    'services.andUp': '& Up',
    'services.city': 'City',
    'services.availability': 'Availability',
    'services.availableNow': 'Available Now',
    'services.verifiedOnly': 'Verified Providers Only',
    'services.notAvailable': 'Currently Unavailable',
    'services.book': 'Book',

    // Service Details Page
    'serviceDetails.verifiedProvider': 'Verified Service Provider',
    'serviceDetails.rating': 'rating',
    'serviceDetails.description': 'Service Description',
    'serviceDetails.includes': 'What\'s Included',
    'serviceDetails.addons': 'Optional Add-ons',
    'serviceDetails.provider': 'Service Provider',
    'serviceDetails.viewProfile': 'View Profile',
    'serviceDetails.contactUs': 'Contact Us',
    'serviceDetails.reviews': 'Reviews',
    'serviceDetails.reviewsCount': 'reviews',
    'serviceDetails.ratingStats': 'Rating Statistics',
    'serviceDetails.loadMore': 'Load More Reviews',
    'serviceDetails.memberSince': 'Member Since',
    'serviceDetails.completedJobs': 'Completed Jobs',
    'serviceDetails.save': 'Save',
    'serviceDetails.bookNow': 'Book Now',
    'serviceDetails.bookLater': 'Book Later',
    'serviceDetails.moneyBack': 'Money-back Guarantee',
    'serviceDetails.certified': 'Certified Provider',
    'serviceDetails.sameDay': 'Same-day Service',

    // Booking Page
    'booking.title': 'Complete Booking',
    'booking.subtitle': 'Complete the details to confirm your booking',
    'booking.step.address': 'Address',
    'booking.step.datetime': 'Date & Time',
    'booking.step.review': 'Review',
    'booking.step.payment': 'Payment',
    'booking.selectAddress': 'Select Address',
    'booking.selectAddressDesc': 'Choose service delivery address',
    'booking.addNewAddress': 'Add New Address',
    'booking.addressLabel': 'Address Label',
    'booking.addressLabelPlaceholder': 'e.g., Home, Work',
    'booking.address': 'Address',
    'booking.addressPlaceholder': 'Street and District',
    'booking.cityLabel': 'City',
    'booking.cityPlaceholder': 'Riyadh',
    'booking.phone': 'Phone Number',
    'booking.phonePlaceholder': '+966 5X XXX XXXX',
    'booking.additionalDetails': 'Additional Details',
    'booking.additionalDetailsPlaceholder': 'Villa number, Floor, location description...',
    'booking.selectDateTime': 'Select Date & Time',
    'booking.selectDateTimeDesc': 'Choose a convenient time for you',
    'booking.date': 'Date',
    'booking.availableTimes': 'Available Times',
    'booking.selectDateFirst': 'Select date first',
    'booking.optionalAddons': 'Optional Add-ons',
    'booking.notes': 'Additional Notes (Optional)',
    'booking.notesPlaceholder': 'Any additional details you\'d like to share...',
    'booking.reviewOrder': 'Review Order',
    'booking.reviewOrderDesc': 'Verify all details before proceeding',
    'booking.serviceAddress': 'Service Address',
    'booking.appointment': 'Appointment',
    'booking.at': 'at',
    'booking.expectedDuration': 'Expected duration',
    'booking.addonsSelected': 'Add-ons',
    'booking.yourNotes': 'Your Notes',
    'booking.paymentTitle': 'Payment',
    'booking.paymentDesc': 'Choose your payment method',
    'booking.discountCode': 'Discount Code',
    'booking.discountCodePlaceholder': 'Enter discount code',
    'booking.apply': 'Apply',
    'booking.discountApplied': 'Discount applied',
    'booking.creditCard': 'Credit Card',
    'booking.cardDescription': 'Visa, Mastercard, Mada',
    'booking.recommended': 'Recommended',
    'booking.wallet': 'Digital Wallet',
    'booking.walletBalance': 'Balance',
    'booking.insufficientBalance': 'Insufficient Balance',
    'booking.cashOnDelivery': 'Cash on Delivery',
    'booking.cashDescription': 'Pay cash when service is delivered',
    'booking.cardNumber': 'Card Number',
    'booking.expiryDate': 'Expiry Date',
    'booking.cardHolder': 'Card Holder Name',
    'booking.cardHolderPlaceholder': 'Name as written on card',
    'booking.securePayment': 'All transactions are encrypted and secured',
    'booking.previous': 'Previous',
    'booking.confirmBooking': 'Confirm Booking & Pay',
    'booking.orderSummary': 'Order Summary',
    'booking.servicePrice': 'Service Price',
    'booking.discount': 'Discount',
    'booking.total': 'Total',
    'booking.freeCancellation': 'Free cancellation before 24 hours',

    // Categories
    'category.homeCleaning': 'Home Cleaning',
    'category.carMaintenance': 'Car Maintenance',
    'category.techServices': 'Tech Services',
    'category.generalMaintenance': 'General Maintenance',
    'category.paintDecor': 'Paint & Decor',
    'category.electrical': 'Electrical',

    // Cities
    'city.riyadh': 'Riyadh',
    'city.jeddah': 'Jeddah',
    'city.dammam': 'Dammam',
    'city.makkah': 'Makkah',
    'city.madinah': 'Madinah',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar');
  const [direction, setDirection] = useState<Direction>('rtl');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'ar' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
      setDirection(savedLanguage === 'ar' ? 'rtl' : 'ltr');
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const newDirection = lang === 'ar' ? 'rtl' : 'ltr';
    setDirection(newDirection);
    localStorage.setItem('language', lang);
    document.documentElement.dir = newDirection;
    document.documentElement.lang = lang;
    document.body.dir = newDirection;
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ar] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, direction, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
